create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text default '',phone text default '',role text default 'user' check(role in('user','admin')),balance_rwf bigint default 0 check(balance_rwf>=0),created_at timestamptz default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),title text not null,description text default '',reward_rwf bigint not null check(reward_rwf>0),slots int not null default 1,status text default 'open' check(status in('open','closed')),created_by uuid references public.profiles(id),created_at timestamptz default now());
create table if not exists public.task_claims(id uuid primary key default gen_random_uuid(),task_id uuid references public.tasks(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,status text default 'claimed',claimed_at timestamptz default now(),unique(task_id,user_id));
create table if not exists public.deposits(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,network text check(network in('MTN','AIRTEL')),amount_rwf bigint check(amount_rwf>0),sender_phone text,transaction_id text,status text default 'pending' check(status in('pending','approved','rejected')),created_at timestamptz default now(),reviewed_at timestamptz,reviewed_by uuid);
create table if not exists public.withdrawals(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,network text check(network in('MTN','AIRTEL')),amount_rwf bigint check(amount_rwf>0),phone text,status text default 'pending' check(status in('pending','paid','rejected')),created_at timestamptz default now(),reviewed_at timestamptz,reviewed_by uuid);
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,type text,amount_rwf bigint,status text default 'completed',reference_id uuid,created_at timestamptz default now());

create or replace function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,phone) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'phone','')) on conflict do nothing; return new; end$$;
drop trigger if exists make_profile on auth.users; create trigger make_profile after insert on auth.users for each row execute procedure public.new_profile();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;

alter table public.profiles enable row level security; alter table public.tasks enable row level security; alter table public.task_claims enable row level security; alter table public.deposits enable row level security; alter table public.withdrawals enable row level security; alter table public.transactions enable row level security;
create policy "profile read" on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy "profile admin update" on public.profiles for update using(public.is_admin());
create policy "tasks read" on public.tasks for select using(true);
create policy "tasks admin" on public.tasks for all using(public.is_admin()) with check(public.is_admin());
create policy "claims read" on public.task_claims for select using(user_id=auth.uid() or public.is_admin());
create policy "claims insert" on public.task_claims for insert with check(user_id=auth.uid());
create policy "claims admin" on public.task_claims for update using(public.is_admin());
create policy "deposit read" on public.deposits for select using(user_id=auth.uid() or public.is_admin());
create policy "deposit insert" on public.deposits for insert with check(user_id=auth.uid());
create policy "deposit admin" on public.deposits for update using(public.is_admin());
create policy "withdraw read" on public.withdrawals for select using(user_id=auth.uid() or public.is_admin());
create policy "withdraw insert" on public.withdrawals for insert with check(user_id=auth.uid());
create policy "withdraw admin" on public.withdrawals for update using(public.is_admin());
create policy "transaction read" on public.transactions for select using(user_id=auth.uid() or public.is_admin());

create or replace function public.approve_deposit(p_id uuid) returns void language plpgsql security definer set search_path=public as $$declare d public.deposits;begin if not public.is_admin() then raise exception 'not authorized';end if;select * into d from public.deposits where id=p_id for update;if d.status<>'pending' then raise exception 'already reviewed';end if;update public.deposits set status='approved',reviewed_at=now(),reviewed_by=auth.uid() where id=p_id;update public.profiles set balance_rwf=balance_rwf+d.amount_rwf where id=d.user_id;insert into public.transactions(user_id,type,amount_rwf,reference_id) values(d.user_id,'deposit',d.amount_rwf,d.id);end$$;
create or replace function public.reject_deposit(p_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin() then raise exception 'not authorized';end if;update public.deposits set status='rejected',reviewed_at=now(),reviewed_by=auth.uid() where id=p_id and status='pending';end$$;
create or replace function public.request_withdrawal(p_network text,p_amount bigint,p_phone text) returns uuid language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();wid uuid;begin update public.profiles set balance_rwf=balance_rwf-p_amount where id=uid and balance_rwf>=p_amount;if not found then raise exception 'insufficient balance';end if;insert into public.withdrawals(user_id,network,amount_rwf,phone) values(uid,p_network,p_amount,p_phone) returning id into wid;insert into public.transactions(user_id,type,amount_rwf,status,reference_id) values(uid,'withdraw',-p_amount,'pending',wid);return wid;end$$;
create or replace function public.mark_withdraw_paid(p_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin() then raise exception 'not authorized';end if;update public.withdrawals set status='paid',reviewed_at=now(),reviewed_by=auth.uid() where id=p_id and status='pending';update public.transactions set status='completed' where reference_id=p_id and type='withdraw';end$$;
create or replace function public.claim_task(p_task uuid) returns uuid language plpgsql security definer set search_path=public as $$declare cid uuid;begin insert into public.task_claims(task_id,user_id) values(p_task,auth.uid()) returning id into cid;return cid;exception when unique_violation then raise exception 'already claimed';end$$;
grant execute on function public.approve_deposit(uuid) to authenticated;grant execute on function public.reject_deposit(uuid) to authenticated;grant execute on function public.request_withdrawal(text,bigint,text) to authenticated;grant execute on function public.mark_withdraw_paid(uuid) to authenticated;grant execute on function public.claim_task(uuid) to authenticated;